package test:out-params;

interface arithmetic {
  variant divide-error {
    divide-by-zero,
  }

  divide: func(
    in dividend: u32,
    in divisor: u32,
    out remainder: u32,
  ) -> result<_, divide-error>;
}

world calculator {
  import arithmetic;
}
